# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot = {
    initrd = {
      availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" "i8042" "i915" "snd-bt-sco" ];
      luks.devices = [ { name = "root"; device = "/dev/sda2"; } ];
      supportedFilesystems = [ "zfs" ];
    };
    kernelModules = [ "kvm-intel" ];
    kernelParams = [ "systemd.legacy_systemd_cgroup_controller=yes" ];
  };

  hardware = {
    enableAllFirmware = true;

    bluetooth.enable = true;
    opengl = {
      enable = true;
      extraPackages = [ pkgs.vaapiIntel ];
      driSupport32Bit = true;
    };
    cpu.intel.updateMicrocode = true;
    pulseaudio = {
      enable = true;
      package = pkgs.pulseaudioFull;
    };
  };

  powerManagement.enable = true;

  services.xserver.config = ''
    # Match on all types of devices but tablet devices and joysticks
    Section "InputClass"
      Identifier "libinput pointer catchall"
      MatchIsPointer "on"
      MatchDevicePath "/dev/input/event*"
      Driver "libinput"
    EndSection
    
    #Section "InputClass"
    #  Identifier "libinput keyboard catchall"
    #  MatchIsKeyboard "on"
    #  MatchDevicePath "/dev/input/event*"
    #  Driver "libinput"
    #EndSection
    
    Section "InputClass"
      Identifier "libinput touchpad catchall"
      MatchIsTouchpad "on"
      MatchDevicePath "/dev/input/event*"
      Driver "libinput"
    EndSection
    
    Section "InputClass"
      Identifier "libinput touchscreen catchall"
      MatchIsTouchscreen "on"
      MatchDevicePath "/dev/input/event*"
      Driver "libinput"
    EndSection
    
    Section "InputClass"
      Identifier "libinput tablet catchall"
      MatchIsTablet "on"
      MatchDevicePath "/dev/input/event*"
      Driver "libinput"
    EndSection
  '';

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A767-904A";
      fsType = "vfat";
    };

  fileSystems."/" =
    { device = "zroot/root/nixos";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "zroot/home";
      fsType = "zfs";
    };

  fileSystems."/home/joerg/Musik/podcasts" =
    { device = "/home/joerg/gPodder/Downloads";
      fsType = "none";
      options = ["bind"];
    };

  fileSystems."/home/joerg/web/privat" =
    { device = "/home/joerg/web/private";
      fsType = "none";
      options = ["bind"];
    };

  fileSystems."/tmp" =
    { device = "zroot/tmp";
      fsType = "zfs";
    };

  fileSystems."none" =
    { device = "/dev/zvol/zroot/swap";
      fsType = "swap";
      options = ["discard"];
    };

  nix.maxJobs = lib.mkDefault 4;
}
