# radicle-mirror: mirrors GitHub repositories to the local Radicle node.
#
# Webhook: https://radicle-mirror.thalheim.io/github
#
# The GitHub App is installed on the repos to mirror. App ID lives in this
# file, the private key comes from `clan vars set` (GitHub-generated .pem),
# webhook secret and Radicle identity key are generated by clan vars.
{
  config,
  pkgs,
  self,
  ...
}:
let
  domain = "radicle-mirror.thalheim.io";
  port = 4128;
  gen = config.clan.core.vars.generators;
  # secrets are root-owned; the DynamicUser service reads them via
  # systemd LoadCredential
  credsDir = "/run/credentials/radicle-mirror.service";
in
{
  imports = [ self.inputs.radicle-mirror.nixosModules.default ];

  services.radicle-mirror = {
    enable = true;
    package = self.inputs.radicle-mirror.packages.${pkgs.system}.default;
    addr = "127.0.0.1:${toString port}";
    ghAppId = 4627581;
    p2pListen = [ "0.0.0.0:8776" ];
    p2pExternalAddresses = [ "radicle.thalheim.io:8776" ];
    mirroredForks = [
      "Mic92/nixpkgs"
      "Mic92/nix-vm-test"
      "Mic92/punchcard"
      "Mic92/nix-1"
    ];
    ghAppKeyPath = "${credsDir}/gh-app-key";
    webhookSecretPath = "${credsDir}/webhook-secret";
    radicleKeyPath = "${credsDir}/radicle-key";
  };

  systemd.services.radicle-mirror.serviceConfig.LoadCredential = [
    "gh-app-key:${gen.radicle-mirror-github-key.files.private-key.path}"
    "webhook-secret:${gen.radicle-mirror-github.files.webhook-secret.path}"
    "radicle-key:${gen.radicle-mirror-key.files.radicle-key.path}"
  ];

  # radicle P2P, so peers can fetch from radicle.thalheim.io directly
  networking.firewall.allowedTCPPorts = [ 8776 ];

  services.nginx.virtualHosts.${domain} = {
    useACMEHost = "thalheim.io";
    forceSSL = true;
    locations."/".extraConfig = ''
      proxy_pass http://127.0.0.1:${toString port};
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    '';
  };

  clan.core.vars.generators.radicle-mirror-github = {
    files.webhook-secret = { };
    runtimeInputs = [ pkgs.xkcdpass ];
    script = ''
      xkcdpass -n 6 -d - > "$out/webhook-secret"
    '';
  };

  # Populated via `clan vars set` from the .pem GitHub generates.
  clan.core.vars.generators.radicle-mirror-github-key = {
    files.private-key = { };
    prompts.private-key = {
      description = "GitHub App private key (PEM) for radicle-mirror";
      type = "multiline";
      persist = true;
    };
    script = ''
      cp "$prompts/private-key" "$out/private-key"
    '';
  };

  # Radicle node identity used for pushing the mirrors.
  clan.core.vars.generators.radicle-mirror-key = {
    files.radicle-key = { };
    runtimeInputs = [ pkgs.openssh ];
    script = ''
      ssh-keygen -t ed25519 -N "" -C radicle-mirror -f "$out/radicle-key"
      rm "$out/radicle-key.pub"
    '';
  };
}
