{
  pkgs,
  lib,
  inputs,
  ...
}:

let
  firefoxExtensions = pkgs.callPackages ../../pkgs/firefox-extensions { };
  micsSkillsPkgs = inputs.mics-skills.packages.${pkgs.stdenv.hostPlatform.system};

  librewolfPath =
    if pkgs.stdenv.isDarwin then
      "/Applications/Nix Casks/LibreWolf.app/Contents/MacOS/librewolf"
    else
      "${pkgs.librewolf}/bin/librewolf";
in
{
  # LibreWolf is installed via darwinModules/nix-casks.nix on macOS
  home.packages = lib.optionals pkgs.stdenv.isLinux [
    # noctalia writes ~/.cache/wal/colors.json (pywalfox template) and calls
    # `pywalfox update` so the browser chrome follows the niri/noctalia palette.
    pkgs.pywalfox-native
    (pkgs.librewolf.override {
      extraPolicies = import ../../pkgs/librewolf-policies.nix {
        inherit (pkgs) lib stdenv;
        inherit (micsSkillsPkgs) browser-cli-extension;
        inherit (firefoxExtensions) chrome-tab-gc-extension;
      };
    })
  ];

  # Tell browser-cli where LibreWolf is so browsh can find it
  xdg.configFile."browser-cli/config.toml".text = ''
    firefox_path = "${librewolfPath}"
  '';

  # Native messaging host so the pywalfox addon can read noctalia colors.
  home.file.".librewolf/native-messaging-hosts/pywalfox.json" = lib.mkIf pkgs.stdenv.isLinux {
    text = builtins.toJSON {
      name = "pywalfox";
      description = "Automatically theme your browser using the colors generated by Pywal";
      path = "${pkgs.pywalfox-native}/bin/pywalfox";
      type = "stdio";
      allowed_extensions = [ "pywalfox@frewacom.org" ];
    };
  };

  # Register native messaging host so the browser extension can talk to browser-cli
  home.activation.installBrowserCliHost = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    ${micsSkillsPkgs.browser-cli}/bin/browser-cli --install-host
  '';
}
