# Generated by generate-sources.py
# DO NOT EDIT MANUALLY
{ fetchurl }:

{
  version = "8.0.4";
  keyAccId = "24441";
  clientId = "148";

  sources = [
    {
      name = "linuxexe64";
      src = fetchurl {
        url = "https://dls.photoprintit.com/download/Data/24441-de_DE/hps/8.0.4/148-linuxexe64-8.0.4_70378ffd6e09f7cb0c7eae4d7d44e9cc.7z";
        hash = "sha256-xo6mw2VHqbm6KaC5lK1NpC4OCvishFlKh3g8ukx8OSs=";
      };
    }
    {
      name = "linuxlib64";
      src = fetchurl {
        url = "https://dls.photoprintit.com/download/Data/generic-data/hps/8.0.4/148-linuxlib64-8.0.4_522676f77b5f014a89ce408d30bd1093.7z";
        hash = "sha256-bouG+2UsytQMns4LMpx9+DJbNMyBB9xYPToIQtHjOqo=";
      };
    }
    {
      name = "backgrounds";
      src = fetchurl {
        url = "https://dls.photoprintit.com/download/Data/generic-data/hps/8.0.4/148-backgrounds-8.0.4_2ba84796eff4f7550264c85252ee93a0.7z";
        hash = "sha256-P+/LzZDgphHfcM8DtuAjvQFyi+WESZ8FJ5QAwAhHAKE=";
      };
    }
    {
      name = "decorations";
      src = fetchurl {
        url = "https://dls.photoprintit.com/download/Data/generic-data/hps/8.0.4/148-decorations-8.0.4_6720dbfe3b8f334ece14734faf92043a.7z";
        hash = "sha256-gogxvUE2P1GdANhtepDkShiqmS5gQLT4I/I2MJEEqw0=";
      };
    }
    {
      name = "photofun";
      src = fetchurl {
        url = "https://dls.photoprintit.com/download/Data/24441-de_DE/hps/8.0.4/148-photofun-8.0.4_ff90145f345a2d78dfdb87bc95cc1874.7z";
        hash = "sha256-MBf/mHs4gdeo7FScYNdnhz95WuLm2XZJWnHg9o0qpvc=";
      };
    }
    {
      name = "resources";
      src = fetchurl {
        url = "https://dls.photoprintit.com/download/Data/24441-de_DE/hps/8.0.4/148-resources-8.0.4_60739e7bdb06502ee7e56395e3133f97.7z";
        hash = "sha256-1KxfcuvwbPPssh7Mcu/lLdMCTSyrggDSj13Qyq3/mZ8=";
      };
    }
    {
      name = "startscreen";
      src = fetchurl {
        url = "https://dls.photoprintit.com/download/Data/24441-de_DE/hps/8.0.4/148-startscreen-8.0.4_44bdee78a962b48baea7148913886784.7z";
        hash = "sha256-jAZCMC6n0fyMy4Hi/3UCtnkxEo+8/ZXZcwHWbheqKzc=";
      };
    }
    {
      name = "svgcalendars";
      src = fetchurl {
        url = "https://dls.photoprintit.com/download/Data/generic-data/hps/8.0.4/148-svgcalendars-8.0.4_47631f8722aba64486412ed2f9df02ee.7z";
        hash = "sha256-h+yncVzuoz3+WyU37rzF3AzscIXC9O1kckq+LjaRCmI=";
      };
    }
    {
      name = "svgtemplates";
      src = fetchurl {
        url = "https://dls.photoprintit.com/download/Data/generic-data/hps/8.0.4/148-svgtemplates-8.0.4_28c13e72902d562c5488606582c001bc.7z";
        hash = "sha256-W2nR8v+UFm4g59D+QB9VeVNGI8pPZpuygNacrgNY6xY=";
      };
    }
  ];
}
