#!/usr/bin/env bash

if [ $EUID -ne 0 ]; then
  echo "Must be root!" >&2
  exit 1
fi

cd /
export PATH=$PATH:/usr/local/bin CWD=/
lxc-attach --name login -- sudo -u aurrepo -- aurrepo  --sign --verbose
lxc-attach --name login -- sudo -u aurrepo -- yaourt "$@"
lxc-attach --name login -- sudo -u aurrepo -- aurrepo  --sign --verbose
lxc-attach --name login -- pacman -Sy
