#!/usr/bin/env bash

if [ $EUID -ne 0 ]; then
  echo "Must be root!" >&2
  exit 1
fi

lxc-attach --name login -- sudo -s -u aurrepo -- <<EOF
set -ex
cd "${DIR:-/}"
aurrepo --sign
makepkg --noconfirm "$@"
aurrepo --sign
EOF
