#!/usr/bin/env bash

if [ $EUID -ne 0 ]; then
  echo "Must be root!" >&2
  exit 1
fi

cd "${DIR:-/tmp}"
lxc-attach --name login -- sudo -u aurrepo -- aurrepo --sign --verbose
lxc-attach --name login -- sudo -u aurrepo -- gem2arch "$@"
lxc-attach --name login -- sudo -u aurrepo -- aurrepo --sign --verbose
