#!/usr/bin/env bash

if [ $EUID -ne 0 ]; then
  echo "Must be root!" >&2
  exit 1
fi

nixos-rebuild switch
echo "Press Ctrl-C to apply changes permanently (Rollback in 10s)"
sleep 10
nixos-rebuild switch --rollback
