# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

with builtins;
let
  zfsMapping = {
    "zroot/home" = "/home";
    "zroot/tmp" = "/tmp";
    "zroot/docker" = "/var/lib/docker";
    "zroot/lxc" = "/lxc";
    "zroot/data" = "/data";
    "zroot/data/backup" = "/data/backup";
    "zroot/data/backup/devkid" = "/data/backup/devkid";
    "zroot/data/pacman" = "/data/pacman";
  };

  zfsMounts = map (fs: {
    mountPoint = zfsMapping.${fs};
    device = fs;
    fsType = "zfs";
    options = ["nofail"];
  }) (attrNames zfsMapping);

in {
  imports =
    [ <nixpkgs/nixos/modules/profiles/qemu-guest.nix>
    ];

  boot = {
    initrd = {
	    availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "sd_mod" "sr_mod" ];
	    luks.devices = [ { name = "root"; device = "/dev/sda2"; } ];
	    supportedFilesystems = [ "zfs" ];
    };
  };

  fileSystems = [
    {
      mountPoint = "/boot";
      device = "/dev/disk/by-uuid/56FC-E60D";
      fsType = "vfat";
      options = ["nofail"];
    }
    {
      device = "/lxc/web/rootfs/etc/letsencrypt";
      mountPoint = "/etc/letsencrypt";
      fsType = "none";
      options = ["bind" "nofail"];
    }
    {
      mountPoint = "/";
      device = "zroot/root";
      fsType = "zfs";
    }
  ] ++ zfsMounts;

  nix.maxJobs = lib.mkDefault 8;
}
