# This file was generated by go2nix.
[
  {
    goPackagePath = "github.com/lxc/go-lxc";
    fetch = {
      type = "git";
      url = "https://github.com/lxc/go-lxc";
      rev = "82a07a67a43089687c0cc71ad515cde8d8ae3b8f";
      sha256 = "1wp38p9bhr5qmf5wyifbyripr8viaw50bh8h1sjq2g1fmg525rs1";
    };
  }
  {
    goPackagePath = "github.com/shirou/gopsutil";
    fetch = {
      type = "git";
      url = "https://github.com/shirou/gopsutil";
      rev = "1516eb9ddc5e61ba58874047a98f8b44b5e585e8";
      sha256 = "1pnl1g2l1y5vmnraq97rbm0nirprqvfzxsp6h4xacn1429jdl5bv";
    };
  }
]
