#term=xterm-256color
font=JetBrainsMono Nerd Font:size=13
line-height=18

[desktop-notifications]
command=notify-send --wait --app-name ${app-id} --icon ${app-id} --category ${category} --urgency ${urgency} --expire-time ${expire-time} --hint STRING:image-path:${icon} --hint BOOLEAN:suppress-sound:${muted} --hint STRING:sound-name:${sound-name} --replace-id ${replace-id} ${action-argument} --print-id -- ${title} ${body}
inhibit-when-focused=yes

[bell]
urgent=yes

#[colors]
#background=282828
#foreground=ebdbb2
#regular0=282828
#regular1=cc241d
#regular2=98971a
#regular3=d79921
#regular4=458588
#regular5=b16286
#regular6=689d6a
#regular7=a89984
#bright0=928374
#bright1=fb4934
#bright2=b8bb26
#bright3=fabd2f
#bright4=83a598
#bright5=d3869b
#bright6=8ec07c
#bright7=ebdbb2

# -*- conf -*-
# Tokyo Night (night)

[cursor]
color=c0caf5 283457

[colors]
foreground=c0caf5
background=1a1b26
selection-foreground=c0caf5
selection-background=283457
urls=73daca
regular0=15161e
regular1=f7768e
regular2=9ece6a
regular3=e0af68
regular4=7aa2f7
regular5=bb9af7
regular6=7dcfff
regular7=a9b1d6
bright0=414868
bright1=f7768e
bright2=9ece6a
bright3=e0af68
bright4=7aa2f7
bright5=bb9af7
bright6=7dcfff
bright7=c0caf5
16=ff9e64
17=db4b4b
