[Appearance]
color_scheme_path=~/.config/qt6ct/colors/noctalia.conf
custom_palette=true
icon_theme=breeze-dark
style=Fusion

[Fonts]
fixed="JetBrainsMono Nerd Font,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular"
general="Inter,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular"

[Interface]
activate_item_on_single_click=1
buttonbox_layout=0
dialog_buttons_have_icons=1
menus_have_icons=true
toolbutton_style=4
wheel_scroll_lines=3
