# This file has been generated by node2nix 1.5.3. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "adverb-where-0.0.9" = {
      name = "adverb-where";
      packageName = "adverb-where";
      version = "0.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/adverb-where/-/adverb-where-0.0.9.tgz";
        sha1 = "09c5cddd8d503b9fe5f76e0b8dc5c70a8f193e34";
      };
    };
    "command-exists-1.2.2" = {
      name = "command-exists";
      packageName = "command-exists";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/command-exists/-/command-exists-1.2.2.tgz";
        sha1 = "12819c64faf95446ec0ae07fe6cafb6eb3708b22";
      };
    };
    "commander-2.15.1" = {
      name = "commander";
      packageName = "commander";
      version = "2.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.15.1.tgz";
        sha512 = "1mb8z6hhy74rfdgj3spmk52sdqa5bb2w5wp28z3md1daqcca4vbbsg66wz8hdhrv0fnnmf8yzdkmnw3c373vcccmyizzlnmbpsd6msn";
      };
    };
    "define-properties-1.1.2" = {
      name = "define-properties";
      packageName = "define-properties";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-properties/-/define-properties-1.1.2.tgz";
        sha1 = "83a73f2fea569898fb737193c8f873caf6d45c94";
      };
    };
    "e-prime-0.10.2" = {
      name = "e-prime";
      packageName = "e-prime";
      version = "0.10.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/e-prime/-/e-prime-0.10.2.tgz";
        sha1 = "ea9375eb985636de88013c7a9fb129ad9e15eff8";
      };
    };
    "foreach-2.0.5" = {
      name = "foreach";
      packageName = "foreach";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/foreach/-/foreach-2.0.5.tgz";
        sha1 = "0bee005018aeb260d0a3af3ae658dd0136ec1b99";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "38chm1mh077ksx6hy2sssfz4q29hf0ncb9k6ila7si54zqcpl5fxd1rh6wi82blqp7jcspf4aynr7jqhbsg2yc9y42xpqqp6c1jz2n8";
      };
    };
    "has-symbols-1.0.0" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.0.0.tgz";
        sha1 = "ba1a8f1af2a0fc39650f5c850367704122063b44";
      };
    };
    "no-cliches-0.1.0" = {
      name = "no-cliches";
      packageName = "no-cliches";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/no-cliches/-/no-cliches-0.1.0.tgz";
        sha1 = "f4eb81a551fecde813f8c611e35e64a5118dc38c";
      };
    };
    "object-keys-1.0.11" = {
      name = "object-keys";
      packageName = "object-keys";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-keys/-/object-keys-1.0.11.tgz";
        sha1 = "c54601778ad560f1142ce0e01bcca8b56d13426d";
      };
    };
    "object.assign-4.1.0" = {
      name = "object.assign";
      packageName = "object.assign";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.assign/-/object.assign-4.1.0.tgz";
        sha512 = "3krdp08gvbxvipalq64qy7bm86znxxdb7ap6bjki235qs17i9fsn6hqd22ga31sqyqa6iyy5xjfnnqc7lsck1kaybwsh154mrxcj4bv";
      };
    };
    "passive-voice-0.1.0" = {
      name = "passive-voice";
      packageName = "passive-voice";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/passive-voice/-/passive-voice-0.1.0.tgz";
        sha1 = "16ff91ae40ba0e92c43e671763fdc842a70270b1";
      };
    };
    "too-wordy-0.1.4" = {
      name = "too-wordy";
      packageName = "too-wordy";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/too-wordy/-/too-wordy-0.1.4.tgz";
        sha1 = "8e7b20a7b7a4d8fc3759f4e00c4929993d1b12f0";
      };
    };
    "vscode-jsonrpc-3.5.0" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "3.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-3.5.0.tgz";
        sha1 = "87239d9e166b2d7352245b8a813597804c1d63aa";
      };
    };
    "vscode-languageserver-3.5.1" = {
      name = "vscode-languageserver";
      packageName = "vscode-languageserver";
      version = "3.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-3.5.1.tgz";
        sha512 = "20rg3b1dymhvnkkxjg481ygy13zg0lg35n5bs4fhwl8f8g3lwy53vnfsxcarjnn6zfjbanq0mllqcqaimbf24n99df327g082ghm1a5";
      };
    };
    "vscode-languageserver-protocol-3.5.1" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.5.1.tgz";
        sha512 = "1hajzildw9njhvj7psprgaw4kipjfsi0dw6fw1r1a8nk04plns64f5f2rvzxsj1knm9ad55f2x0d4dcivbg2zi5gii5ggq01ciw7wym";
      };
    };
    "vscode-languageserver-types-3.5.0" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.5.0.tgz";
        sha1 = "e48d79962f0b8e02de955e3f524908e2b19c0374";
      };
    };
    "vscode-uri-1.0.3" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-1.0.3.tgz";
        sha1 = "631bdbf716dccab0e65291a8dc25c23232085a52";
      };
    };
    "weasel-words-0.1.1" = {
      name = "weasel-words";
      packageName = "weasel-words";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/weasel-words/-/weasel-words-0.1.1.tgz";
        sha1 = "7137946585c73fe44882013853bd000c5d687a4e";
      };
    };
  };
in
{
  write-good = nodeEnv.buildNodePackage {
    name = "write-good";
    packageName = "write-good";
    version = "0.11.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/write-good/-/write-good-0.11.3.tgz";
      sha512 = "0sqzdqlvhcf7qqqch5mjxv7ag9hlmkcw8sdg0gdwgk59d7z8nimh66d36aa03kby9jzdkf8aik6ncngddfjd3g1135k82vhxqf8hckw";
    };
    dependencies = [
      sources."adverb-where-0.0.9"
      sources."define-properties-1.1.2"
      sources."e-prime-0.10.2"
      sources."foreach-2.0.5"
      sources."function-bind-1.1.1"
      sources."has-symbols-1.0.0"
      sources."no-cliches-0.1.0"
      sources."object-keys-1.0.11"
      sources."object.assign-4.1.0"
      sources."passive-voice-0.1.0"
      sources."too-wordy-0.1.4"
      sources."weasel-words-0.1.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Naive linter for English prose";
      homepage = "https://github.com/btford/write-good#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
  typescript-language-server = nodeEnv.buildNodePackage {
    name = "typescript-language-server";
    packageName = "typescript-language-server";
    version = "0.1.9";
    src = fetchurl {
      url = "https://registry.npmjs.org/typescript-language-server/-/typescript-language-server-0.1.9.tgz";
      sha1 = "a0b1d7b1a1956abac8ffca5256d6eebcef659a3d";
    };
    dependencies = [
      sources."command-exists-1.2.2"
      sources."commander-2.15.1"
      sources."vscode-jsonrpc-3.5.0"
      sources."vscode-languageserver-3.5.1"
      sources."vscode-languageserver-protocol-3.5.1"
      sources."vscode-languageserver-types-3.5.0"
      sources."vscode-uri-1.0.3"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Language Server Protocol (LSP) implementation for TypeScript using tsserver";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = false;
  };
}