# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    "${modulesPath}/installer/scan/not-detected.nix"
  ];

  # on demand
  services.fwupd.enable = false;

  # xps
  #boot.initrd.availableKernelModules = [
  #  "xhci_pci"
  #  "ehci_pci"
  #  # required on thinkpad
  #  #"ahci"
  #  "usb_storage"
  #  "sd_mod"
  #  "rtsx_pci_sdmmc"
  #  "nvme"
  #];
  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "sdhci_pci" ];
  boot.kernelModules = [ "kvm-intel" ];

  # for zfs
  networking.hostId = "8425e349";
  boot.zfs.enableUnstable = true;

  hardware = {
    bluetooth.enable = true;
    opengl = {
      enable = true;
      driSupport32Bit = true;
    };
    #pulseaudio = {
    #  enable = true;
    #  package = pkgs.pulseaudioFull;
    #};
  };

  # for pactl
  environment.systemPackages = with pkgs; [ pulseaudio ];

  hardware.pulseaudio.enable = false;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    #jack.enable = true;
    # use the example session manager
    media-session.enable = true;
  };
  security.rtkit.enable = true;

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/1638-625C";
    fsType = "vfat";
    options = [ "nofail" ];
  };

  fileSystems."/" = {
    device = "zroot/root/nixos";
    fsType = "zfs";
  };

  fileSystems."/home" = {
    device = "zroot/root/home";
    fsType = "zfs";
    options = [ "nofail" ];
  };

  fileSystems."/home/joerg/Musik/podcasts" = {
    device = "/home/joerg/gPodder/Downloads";
    fsType = "none";
    options = [ "bind" "nofail" ];
  };

  fileSystems."/tmp" = {
    device = "zroot/root/tmp";
    fsType = "zfs";
    options = [ "nofail" ];
  };

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
