[package]
name = "direnv-instant"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "0.29", features = ["signal", "process", "fs", "term", "poll", "user", "socket", "uio"] }
libc = "0.2"