#!/usr/bin/env python

import json
import shutil
import os
import syslog
import sys
from subprocess import Popen, PIPE


def upload_cachix(cachix_name: str, cachix_config: str, hydra_json: str) -> None:
    with open(hydra_json) as f:
        data = json.load(f)
    with Popen(
        ["cachix", "-c", cachix_config, "push", cachix_name], stdin=PIPE, text=True
    ) as proc:
        assert proc.stdin
        for output in data["outputs"]:
            proc.stdin.write(output["path"])
            proc.stdin.write("\n")


def require_env(name: str) -> str:
    val = os.environ.get(name)
    if val is None:
        syslog.syslog(f"{val} environment variable is not set")
        sys.exit(1)
    return val


def main() -> None:
    syslog.syslog(f"upload to cachix finished")
    hydra_json = require_env("HYDRA_JSON")
    cachix_config = require_env("CACHIX_CONFIG")
    cachix_name = require_env("CACHIX_NAME")

    syslog.syslog(f"upload to cachix started")
    try:
        upload_cachix(cachix_name, cachix_config, hydra_json)
    except Exception as e:
        syslog.syslog(f"uploading to cachix failed: {e}")
        sys.exit(1)
    syslog.syslog(f"upload to cachix finished")


if __name__ == "__main__":
    main()
