#!/usr/bin/env python

import json
import shutil
import sys


def main() -> None:
    print('hello world')
    shutil.copyfile(sys.environ["HYDRA_JSON"], "/tmp/hydra.json")
    with open(sys.environ["HYDRA_JSON"]) as f:
        data = json.load(f)


if __name__ == "__main__":
    main()
