#!/usr/bin/env bash

set -eux -o pipefail

sink=alsa_output.pci-0000_00_1f.3.analog-stereo

if pamixer --get-mute --sink="$sink"; then
    pamixer --sink=$sink --unmute
    paplay --device=$sink
    pamixer --sink=$sink --mute
else
    paplay --device=$sink
fi
