# Generated by spacemacs2nix.el
p:
let checked = n:
  let
    n' = builtins.replaceStrings ["+"] ["-plus"] n;
    p' = p.${n'} or null;
  in if p'.meta.broken or false then null else p';
in
{
  "templates" = [
    (checked "yatemplate")
  ];
  "helm" = [
    (checked "ace-jump-helm-line")
    (checked "auto-highlight-symbol")
    (checked "bookmark")
    (checked "helm")
    (checked "helm-ag")
    (checked "helm-descbinds")
    (checked "helm-flx")
    (checked "helm-ls-git")
    (checked "helm-make")
    (checked "helm-mode-manager")
    (checked "helm-projectile")
    (checked "helm-swoop")
    (checked "helm-themes")
    (checked "helm-spacemacs-help")
    (checked "helm-spacemacs-faq")
    (checked "helm-xref")
    (checked "imenu")
    (checked "persp-mode")
    (checked "popwin")
    (checked "projectile")
  ];
  "auto-completion" = [
    (checked "auto-yasnippet")
    (checked "auto-complete")
    (checked "ac-ispell")
    (checked "company")
    (checked "company-box")
    (checked "all-the-icons")
    (checked "company-quickhelp")
    (checked "company-statistics")
    (checked "counsel")
    (checked "fuzzy")
    (checked "helm-company")
    (checked "helm-c-yasnippet")
    (checked "hippie-exp")
    (checked "ivy-yasnippet")
    (checked "smartparens")
    (checked "yasnippet")
    (checked "yasnippet-snippets")
  ];
  "ivy" = [
    (checked "auto-highlight-symbol")
    (checked "bookmark")
    (checked "counsel")
    (checked "counsel-projectile")
    (checked "evil")
    (checked "flx")
    (checked "helm-make")
    (checked "imenu")
    (checked "ivy")
    (checked "ivy-hydra")
    (checked "ivy-rich")
    (checked "ivy-spacemacs-help")
    (checked "ivy-xref")
    (checked "org")
    (checked "persp-mode")
    (checked "projectile")
    (checked "recentf")
    (checked "smex")
    (checked "swiper")
    (checked "wgrep")
  ];
  "floobits" = [
    (checked "floobits")
  ];
  "spell-checking" = [
    (checked "auto-dictionary")
    (checked "flyspell")
    (checked "flyspell-correct")
    (checked "flyspell-correct-ivy")
    (checked "flyspell-correct-helm")
    (checked "flyspell-correct-popup")
    (checked "flyspell-popup")
  ];
  "syntax-checking" = [
    (checked "flycheck")
    (checked "flycheck-pos-tip")
    (checked "popwin")
  ];
  "clojure" = [
    (checked "cider")
    (checked "cider-eval-sexp-fu")
    (checked "clj-refactor")
    (checked "clojure-mode")
    (checked "clojure-snippets")
    (checked "company")
    (checked "eldoc")
    (checked "evil-cleverparens")
    (checked "flycheck")
    (checked "flycheck-clojure")
    (checked "flycheck-clj-kondo")
    (checked "flycheck-joker")
    (checked "ggtags")
    (checked "counsel-gtags")
    (checked "helm-gtags")
    (checked "org")
    (checked "parinfer")
    (checked "popwin")
    (checked "sayid")
    (checked "smartparens")
    (checked "subword")
  ];
  "perl6" = [
    (checked "company")
    (checked "evil")
    (checked "flycheck")
    (checked "flycheck-perl6")
    (checked "perl6-mode")
  ];
  "scala" = [
    (checked "ensime")
    (checked "lsp-mode")
    (checked "ggtags")
    (checked "counsel-gtags")
    (checked "helm-gtags")
    (checked "noflet")
    (checked "org")
    (checked "scala-mode")
    (checked "sbt-mode")
  ];
  "c-c++" = [
    (checked "cc-mode")
    (checked "clang-format")
    (checked "company-c-headers")
    (checked "cpp-auto-include")
    (checked "disaster")
    (checked "eldoc")
    (checked "flycheck")
    (checked "gdb-mi")
    (checked "google-c-style")
    (checked "helm-cscope")
    (checked "org")
    (checked "projectile")
    (checked "realgud")
    (checked "semantic")
    (checked "srefactor")
    (checked "stickyfunc-enhance")
    (checked "xcscope")
    (checked "ccls")
    (checked "cquery")
    (checked "dap-mode")
    (checked "company-rtags")
    (checked "counsel-gtags")
    (checked "flycheck-rtags")
    (checked "ggtags")
    (checked "helm-gtags")
    (checked "helm-rtags")
    (checked "ivy-rtags")
    (checked "rtags")
    (checked "company-ycmd")
    (checked "flycheck-ycmd")
    (checked "ycmd")
  ];
  "restructuredtext" = [
    (checked "auto-complete")
    (checked "auto-complete-rst")
    (checked "linum")
    (checked "rst")
    (checked "rst-directives")
    (checked "rst-lists")
    (checked "flyspell")
    (checked "smartparens")
    (checked "yasnippet")
  ];
  "go" = [
    (checked "company")
    (checked "company-go")
    (checked "counsel-gtags")
    (checked "eldoc")
    (checked "flycheck")
    (checked "flycheck-golangci-lint")
    (checked "ggtags")
    (checked "helm-gtags")
    (checked "go-eldoc")
    (checked "go-fill-struct")
    (checked "go-gen-test")
    (checked "go-guru")
    (checked "go-impl")
    (checked "go-mode")
    (checked "go-rename")
    (checked "go-tag")
    (checked "godoctor")
    (checked "popwin")
  ];
  "ess" = [
    (checked "company")
    (checked "flycheck")
    (checked "ess")
    (checked "ess-R-data-view")
    (checked "golden-ratio")
    (checked "org")
  ];
  "elm" = [
    (checked "company")
    (checked "elm-mode")
    (checked "elm-test-runner")
    (checked "flycheck")
    (checked "flycheck-elm")
    (checked "popwin")
    (checked "smartparens")
  ];
  "gpu" = [
    (checked "company-glsl")
    (checked "cuda-mode")
    (checked "glsl-mode")
    (checked "opencl-mode")
  ];
  "factor" = [
    (checked "fuel")
    (checked "yasnippet")
  ];
  "json" = [
    (checked "add-node-modules-path")
    (checked "flycheck")
    (checked "json-mode")
    (checked "json-navigator")
    (checked "json-reformat")
    (checked "json-snatcher")
    (checked "prettier-js")
    (checked "web-beautify")
  ];
  "ipython-notebook" = [
    (checked "company")
    (checked "ein")
    (checked "ob-ipython")
    (checked "websocket")
    (checked "request")
    (checked "request-deferred")
    (checked "dash")
    (checked "s")
    (checked "skewer-mode")
  ];
  "jsonnet" = [
    (checked "jsonnet-mode")
    (checked "flycheck")
  ];
  "java" = [
    (checked "company")
    (checked "dap-mode")
    (checked "flycheck")
    (checked "ggtags")
    (checked "gradle-mode")
    (checked "counsel-gtags")
    (checked "helm-gtags")
    (checked "java-mode")
    (checked "maven-test-mode")
    (checked "meghanada")
    (checked "mvn")
    (checked "lsp-java")
    (checked "org")
    (checked "smartparens")
  ];
  "mercury" = [
    (checked "metal-mercury-mode")
    (checked "mercury-mode")
    (checked "flycheck")
    (checked "flycheck-mercury")
    (checked "smartparens")
  ];
  "dhall" = [
    (checked "dhall-mode")
  ];
  "swift" = [
    (checked "flycheck")
    (checked "swift-mode")
  ];
  "perl5" = [
    (checked "company-plsense")
    (checked "cperl-mode")
    (checked "flycheck")
    (checked "org")
    (checked "realgud")
    (checked "smartparens")
  ];
  "racket" = [
    (checked "company")
    (checked "company-quickhelp")
    (checked "ggtags")
    (checked "counsel-gtags")
    (checked "evil-cleverparens")
    (checked "helm-gtags")
    (checked "racket-mode")
  ];
  "crystal" = [
    (checked "ameba")
    (checked "company")
    (checked "crystal-mode")
    (checked "flycheck")
    (checked "flycheck-crystal")
    (checked "inf-crystal")
    (checked "ob-crystal")
    (checked "play-crystal")
  ];
  "typescript" = [
    (checked "add-node-modules-path")
    (checked "company")
    (checked "eldoc")
    (checked "emmet-mode")
    (checked "flycheck")
    (checked "smartparens")
    (checked "tide")
    (checked "typescript-mode")
    (checked "import-js")
    (checked "web-mode")
    (checked "yasnippet")
  ];
  "kotlin" = [
    (checked "flycheck")
    (checked "flycheck-kotlin")
    (checked "ggtags")
    (checked "helm-gtags")
    (checked "kotlin-mode")
  ];
  "markdown" = [
    (checked "company")
    (checked "company-emoji")
    (checked "emoji-cheat-sheet-plus")
    (checked "gh-md")
    (checked "markdown-mode")
    (checked "markdown-toc")
    (checked "mmm-mode")
    (checked "org")
    (checked "smartparens")
    (checked "vmd-mode")
  ];
  "common-lisp" = [
    (checked "auto-highlight-symbol")
    (checked "common-lisp-snippets")
    (checked "evil")
    (checked "evil-cleverparens")
    (checked "ggtags")
    (checked "counsel-gtags")
    (checked "helm")
    (checked "helm-gtags")
    (checked "parinfer")
    (checked "rainbow-identifiers")
    (checked "slime")
    (checked "slime-company")
  ];
  "elixir" = [
    (checked "alchemist")
    (checked "company")
    (checked "counsel-gtags")
    (checked "dap-mode")
    (checked "elixir-mode")
    (checked "evil-matchit")
    (checked "flycheck")
    (checked "flycheck-credo")
    (checked "flycheck-mix")
    (checked "ggtags")
    (checked "helm-gtags")
    (checked "ob-elixir")
    (checked "popwin")
    (checked "smartparens")
  ];
  "prolog" = [
    (checked "prolog")
    (checked "ediprolog")
  ];
  "ocaml" = [
    (checked "company")
    (checked "dune")
    (checked "flycheck")
    (checked "flycheck-ocaml")
    (checked "ggtags")
    (checked "counsel-gtags")
    (checked "helm-gtags")
    (checked "merlin")
    (checked "ocp-indent")
    (checked "smartparens")
    (checked "tuareg")
    (checked "utop")
  ];
  "csv" = [
    (checked "csv-mode")
  ];
  "sql" = [
    (checked "company")
    (checked "org")
    (checked "sql")
    (checked "sql-indent")
    (checked "sqlfmt")
    (checked "sqlup-mode")
  ];
  "scheme" = [
    (checked "company")
    (checked "evil-cleverparens")
    (checked "geiser")
    (checked "ggtags")
    (checked "counsel-gtags")
    (checked "helm-gtags")
    (checked "parinfer")
  ];
  "solidity" = [
    (checked "add-node-modules-path")
    (checked "flycheck")
    (checked "solidity-mode")
    (checked "solidity-flycheck")
  ];
  "plantuml" = [
    (checked "org")
    (checked "plantuml-mode")
  ];
  "asciidoc" = [
    (checked "adoc-mode")
  ];
  "windows-scripts" = [
    (checked "dos")
    (checked "ggtags")
    (checked "counsel-gtags")
    (checked "helm-gtags")
    (checked "powershell")
  ];
  "semantic-web" = [
    (checked "ttl-mode")
    (checked "sparql-mode")
    (checked "org")
  ];
  "forth" = [
    (checked "forth-mode")
  ];
  "haskell" = [
    (checked "cmm-mode")
    (checked "company")
    (checked "company-cabal")
    (checked "company-ghci")
    (checked "company-ghc")
    (checked "ghc")
    (checked "intero")
    (checked "dante")
    (checked "attrap")
    (checked "lsp-haskell")
    (checked "flycheck")
    (checked "flycheck-haskell")
    (checked "ggtags")
    (checked "haskell-mode")
    (checked "haskell-snippets")
    (checked "counsel-gtags")
    (checked "helm-gtags")
    (checked "helm-hoogle")
    (checked "hindent")
    (checked "hlint-refactor")
  ];
  "emacs-lisp" = [
    (checked "auto-compile")
    (checked "company")
    (checked "debug")
    (checked "edebug")
    (checked "eldoc")
    (checked "elisp-slime-nav")
    (checked "emacs-lisp")
    (checked "evil")
    (checked "evil-cleverparens")
    (checked "eval-sexp-fu")
    (checked "flycheck")
    (checked "flycheck-elsa")
    (checked "flycheck-package")
    (checked "ggtags")
    (checked "counsel-gtags")
    (checked "helm-gtags")
    (checked "ielm")
    (checked "macrostep")
    (checked "nameless")
    (checked "overseer")
    (checked "parinfer")
    (checked "rainbow-identifiers")
    (checked "semantic")
    (checked "smartparens")
    (checked "srefactor")
  ];
  "vimscript" = [
    (checked "vimrc-mode")
    (checked "ggtags")
    (checked "counsel-gtags")
    (checked "helm-gtags")
    (checked "dactyl-mode")
  ];
  "julia" = [
    (checked "company-lsp")
    (checked "evil-surround")
    (checked "flycheck")
    (checked "julia-mode")
    (checked "julia-repl")
    (checked "lsp-julia")
  ];
  "idris" = [
    (checked "company")
    (checked "idris-mode")
    (checked "golden-ratio")
    (checked "popwin")
  ];
  "nim" = [
    (checked "company")
    (checked "flycheck")
    (checked "flycheck-nim")
    (checked "nim-mode")
  ];
  "lua" = [
    (checked "company")
    (checked "company-lua")
    (checked "flycheck")
    (checked "ggtags")
    (checked "counsel-gtags")
    (checked "helm-gtags")
    (checked "lua-mode")
  ];
  "rust" = [
    (checked "cargo")
    (checked "company")
    (checked "counsel-gtags")
    (checked "dap-mode")
    (checked "flycheck")
    (checked "flycheck-rust")
    (checked "ggtags")
    (checked "helm-gtags")
    (checked "racer")
    (checked "rust-mode")
    (checked "smartparens")
    (checked "toml-mode")
  ];
  "erlang" = [
    (checked "company")
    (checked "erlang")
    (checked "ggtags")
    (checked "counsel-gtags")
    (checked "helm-gtags")
    (checked "flycheck")
  ];
  "sml" = [
    (checked "sml-mode")
    (checked "ob-sml")
    (checked "smartparens")
  ];
  "fsharp" = [
    (checked "fsharp-mode")
    (checked "ggtags")
    (checked "counsel-gtags")
    (checked "helm-gtags")
  ];
  "groovy" = [
    (checked "company")
    (checked "groovy-imports")
    (checked "groovy-mode")
    (checked "org")
  ];
  "coq" = [
    (checked "company-coq")
    (checked "proof-general")
    (checked "smartparens")
    (checked "vi-tilde-fringe")
  ];
  "yaml" = [
    (checked "company")
    (checked "flycheck")
    (checked "yaml-mode")
  ];
  "pact" = [
    (checked "flycheck")
    (checked "flycheck-pact")
    (checked "pact-mode")
  ];
  "faust" = [
    (checked "company")
    (checked "faust-mode")
    (checked "yasnippet")
  ];
  "purescript" = [
    (checked "add-node-modules-path")
    (checked "company")
    (checked "flycheck")
    (checked "purescript-mode")
    (checked "psci")
    (checked "psc-ide")
    (checked "popwin")
  ];
  "major-modes" = [
    (checked "arduino-mode")
    (checked "ebuild-mode")
    (checked "hoon-mode")
    (checked "logcat")
    (checked "matlab-mode")
    (checked "pkgbuild-mode")
    (checked "qml-mode")
    (checked "scad-mode")
    (checked "stan-mode")
    (checked "thrift")
    (checked "vala-mode")
    (checked "vala-snippets")
    (checked "wolfram-mode")
  ];
  "javascript" = [
    (checked "add-node-modules-path")
    (checked "company")
    (checked "counsel-gtags")
    (checked "dap-mode")
    (checked "evil-matchit")
    (checked "flycheck")
    (checked "ggtags")
    (checked "helm-gtags")
    (checked "imenu")
    (checked "impatient-mode")
    (checked "import-js")
    (checked "js-doc")
    (checked "js2-mode")
    (checked "js2-refactor")
    (checked "livid-mode")
    (checked "nodejs-repl")
    (checked "org")
    (checked "prettier-js")
    (checked "skewer-mode")
    (checked "tern")
    (checked "web-beautify")
  ];
  "latex" = [
    (checked "auctex")
    (checked "auctex-latexmk")
    (checked "company-auctex")
    (checked "company-reftex")
    (checked "evil-matchit")
    (checked "reftex")
    (checked "flycheck")
    (checked "flyspell")
    (checked "ggtags")
    (checked "counsel-gtags")
    (checked "helm-gtags")
    (checked "magic-latex-buffer")
    (checked "smartparens")
    (checked "typo")
    (checked "yasnippet")
    (checked "which-key")
  ];
  "graphviz" = [
    (checked "graphviz-dot-mode")
    (checked "org")
    (checked "smartparens")
  ];
  "php" = [
    (checked "drupal-mode")
    (checked "eldoc")
    (checked "evil-matchit")
    (checked "flycheck")
    (checked "ggtags")
    (checked "counsel-gtags")
    (checked "helm-gtags")
    (checked "php-auto-yasnippets")
    (checked "php-extras")
    (checked "php-mode")
    (checked "phpcbf")
    (checked "phpunit")
    (checked "phpactor")
    (checked "company-phpactor")
    (checked "company-php")
    (checked "geben")
  ];
  "zig" = [
    (checked "zig-mode")
  ];
  "kivy" = [
    (checked "kivy-mode")
  ];
  "protobuf" = [
    (checked "flycheck")
    (checked "protobuf-mode")
  ];
  "d" = [
    (checked "company")
    (checked "company-dcd")
    (checked "d-mode")
    (checked "flycheck")
    (checked "flycheck-dmd-dub")
    (checked "ggtags")
    (checked "counsel-gtags")
    (checked "helm-gtags")
  ];
  "reasonml" = [
    (checked "company")
    (checked "evil-matchit")
    (checked "flycheck")
    (checked "flycheck-ocaml")
    (checked "merlin")
    (checked "popwin")
    (checked "reason-mode")
    (checked "utop")
  ];
  "autohotkey" = [
    (checked "ahk-mode")
  ];
  "alda" = [
    (checked "alda-mode")
  ];
  "csharp" = [
    (checked "company")
    (checked "csharp-mode")
    (checked "evil-matchit")
    (checked "ggtags")
    (checked "counsel-gtags")
    (checked "helm-gtags")
    (checked "omnisharp")
    (checked "flycheck")
  ];
  "asm" = [
    (checked "asm-mode")
    (checked "company")
    (checked "electric-indent-mode")
    (checked "ggtags")
    (checked "counsel-gtags")
    (checked "helm-gtags")
    (checked "nasm-mode")
    (checked "x86-lookup")
  ];
  "ruby" = [
    (checked "bundler")
    (checked "chruby")
    (checked "company")
    (checked "counsel-gtags")
    (checked "dap-mode")
    (checked "enh-ruby-mode")
    (checked "evil-matchit")
    (checked "flycheck")
    (checked "ggtags")
    (checked "helm-gtags")
    (checked "minitest")
    (checked "org")
    (checked "popwin")
    (checked "rake")
    (checked "rbenv")
    (checked "robe")
    (checked "rspec-mode")
    (checked "rubocop")
    (checked "rubocopfmt")
    (checked "ruby-hash-syntax")
    (checked "ruby-mode")
    (checked "ruby-refactor")
    (checked "ruby-test-mode")
    (checked "ruby-tools")
    (checked "rvm")
    (checked "seeing-is-believing")
    (checked "smartparens")
  ];
  "bibtex" = [
    (checked "auctex")
    (checked "org")
    (checked "org-ref")
    (checked "markdown-mode")
    (checked "helm-bibtex")
    (checked "biblio")
    (checked "biblio-core")
  ];
  "html" = [
    (checked "add-node-modules-path")
    (checked "company")
    (checked "company-web")
    (checked "css-mode")
    (checked "emmet-mode")
    (checked "evil-matchit")
    (checked "flycheck")
    (checked "haml-mode")
    (checked "counsel-css")
    (checked "helm-css-scss")
    (checked "impatient-mode")
    (checked "less-css-mode")
    (checked "prettier-js")
    (checked "pug-mode")
    (checked "sass-mode")
    (checked "scss-mode")
    (checked "slim-mode")
    (checked "smartparens")
    (checked "tagedit")
    (checked "web-mode")
    (checked "yasnippet")
    (checked "web-beautify")
  ];
  "octave" = [
    (checked "ggtags")
    (checked "counsel-gtags")
    (checked "helm-gtags")
    (checked "octave")
  ];
  "jr" = [
    (checked "jr-mode")
  ];
  "conda" = [
    (checked "conda")
  ];
  "yang" = [
    (checked "company")
    (checked "flycheck")
    (checked "yang-mode")
  ];
  "python" = [
    (checked "blacken")
    (checked "company")
    (checked "counsel-gtags")
    (checked "cython-mode")
    (checked "dap-mode")
    (checked "eldoc")
    (checked "evil-matchit")
    (checked "flycheck")
    (checked "ggtags")
    (checked "helm-cscope")
    (checked "helm-gtags")
    (checked "helm-pydoc")
    (checked "importmagic")
    (checked "live-py-mode")
    (checked "nose")
    (checked "org")
    (checked "pip-requirements")
    (checked "pipenv")
    (checked "pippel")
    (checked "py-isort")
    (checked "pyenv-mode")
    (checked "pylookup")
    (checked "pytest")
    (checked "python")
    (checked "pyvenv")
    (checked "semantic")
    (checked "smartparens")
    (checked "stickyfunc-enhance")
    (checked "xcscope")
    (checked "yapfify")
    (checked "anaconda-mode")
    (checked "company-anaconda")
    (checked "lsp-python-ms")
  ];
  "dart" = [
    (checked "dart-mode")
    (checked "dart-server")
    (checked "flutter")
    (checked "flycheck")
  ];
  "coffeescript" = [
    (checked "add-node-modules-path")
    (checked "coffee-mode")
    (checked "company")
    (checked "flycheck")
    (checked "ob-coffeescript")
  ];
  "hy" = [
    (checked "company")
    (checked "evil-cleverparens")
    (checked "hy-mode")
    (checked "ob-hy")
    (checked "pyenv-mode")
    (checked "pyvenv")
    (checked "pipenv")
    (checked "smartparens")
  ];
  "agda" = [
    (checked "agda")
    (checked "company")
    (checked "golden-ratio")
  ];
  "shell-scripts" = [
    (checked "company-shell")
    (checked "fish-mode")
    (checked "flycheck")
    (checked "flycheck-bashate")
    (checked "ggtags")
    (checked "counsel-gtags")
    (checked "helm-gtags")
    (checked "insert-shebang")
    (checked "org")
    (checked "sh-script")
  ];
  "phoenix" = [
    (checked "alchemist")
  ];
  "ruby-on-rails" = [
    (checked "feature-mode")
    (checked "projectile-rails")
    (checked "which-key")
  ];
  "vue" = [
    (checked "web-mode")
    (checked "add-node-modules-path")
    (checked "company")
    (checked "evil-matchit")
    (checked "flycheck")
    (checked "prettier-js")
    (checked "smartparens")
    (checked "yasnippet")
  ];
  "react" = [
    (checked "add-node-modules-path")
    (checked "company")
    (checked "emmet-mode")
    (checked "evil-matchit")
    (checked "flycheck")
    (checked "import-js")
    (checked "js-doc")
    (checked "prettier-js")
    (checked "rjsx-mode")
    (checked "smartparens")
    (checked "tern")
    (checked "web-beautify")
    (checked "yasnippet")
  ];
  "emberjs" = [
    (checked "ember-mode")
    (checked "ember-yasnippets")
  ];
  "django" = [
    (checked "pony-mode")
  ];
  "confluence" = [
    (checked "confluence")
    (checked "ox-confluence")
  ];
  "twitter" = [
    (checked "twittering-mode")
  ];
  "wakatime" = [
    (checked "wakatime-mode")
  ];
  "evernote" = [
    (checked "geeknote")
  ];
  "search-engine" = [
    (checked "engine-mode")
  ];
  "nixos" = [
    (checked "company-nixos-options")
    (checked "flycheck")
    (checked "helm-nixos-options")
    (checked "nix-mode")
    (checked "nixos-options")
  ];
  "osx" = [
    (checked "exec-path-from-shell")
    (checked "helm")
    (checked "launchctl")
    (checked "osx-dictionary")
    (checked "osx-trash")
    (checked "osx-clipboard")
    (checked "reveal-in-osx-finder")
    (checked "term")
  ];
  "spotify" = [
    (checked "spotify")
    (checked "helm-spotify-plus")
    (checked "counsel-spotify")
  ];
  "spacemacs-defaults" = [
    (checked "abbrev")
    (checked "archive-mode")
    (checked "bookmark")
    (checked "conf-mode")
    (checked "dired")
    (checked "dired-x")
    (checked "display-line-numbers")
    (checked "electric-indent-mode")
    (checked "ediff")
    (checked "eldoc")
    (checked "help-fns+")
    (checked "hi-lock")
    (checked "image-mode")
    (checked "imenu")
    (checked "linum")
    (checked "occur-mode")
    (checked "package-menu")
    (checked "page-break-lines")
    (checked "process-menu")
    (checked "recentf")
    (checked "savehist")
    (checked "saveplace")
    (checked "subword")
    (checked "tar-mode")
    (checked "uniquify")
    (checked "url")
    (checked "visual-line-mode")
    (checked "whitespace")
    (checked "winner")
    (checked "zone")
  ];
  "spacemacs-evil" = [
    (checked "evil-anzu")
    (checked "evil-args")
    (checked "evil-cleverparens")
    (checked "evil-ediff")
    (checked "evil-escape")
    (checked "evil-exchange")
    (checked "evil-goggles")
    (checked "evil-iedit-state")
    (checked "evil-indent-plus")
    (checked "evil-lion")
    (checked "evil-lisp-state")
    (checked "evil-nerd-commenter")
    (checked "evil-matchit")
    (checked "evil-numbers")
    (checked "evil-surround")
    (checked "evil-textobj-line")
    (checked "evil-tutor")
    (checked "evil-unimpaired")
    (checked "evil-visual-mark-mode")
    (checked "evil-visualstar")
    (checked "hs-minor-mode")
    (checked "linum-relative")
    (checked "vi-tilde-fringe")
    (checked "eldoc")
  ];
  "spacemacs-org" = [
    (checked "flyspell")
    (checked "default-org-config")
    (checked "org-plus-contrib")
    (checked "org-bullets")
    (checked "space-doc")
    (checked "toc-org")
  ];
  "spacemacs-purpose" = [
    (checked "eyebrowse")
    (checked "helm-purpose")
    (checked "ivy-purpose")
    (checked "popwin")
    (checked "spacemacs-purpose-popwin")
    (checked "window-purpose")
  ];
  "spacemacs-completion" = [
    (checked "default-helm-config")
    (checked "default-ivy-config")
    (checked "flx-ido")
    (checked "ido")
    (checked "ido-vertical-mode")
  ];
  "spacemacs-visual" = [
    (checked "ansi-colors")
    (checked "desktop")
    (checked "display-fill-column-indicator")
    (checked "fill-column-indicator")
    (checked "hl-todo")
    (checked "popup")
    (checked "popwin")
    (checked "zoom-frm")
  ];
  "spacemacs-editing-visual" = [
    (checked "hide-comnt")
    (checked "hl-anything")
    (checked "column-enforce-mode")
    (checked "highlight-indentation")
    (checked "highlight-numbers")
    (checked "highlight-parentheses")
    (checked "indent-guide")
    (checked "rainbow-delimiters")
    (checked "volatile-highlights")
    (checked "writeroom-mode")
  ];
  "spacemacs-navigation" = [
    (checked "ace-link")
    (checked "ace-window")
    (checked "auto-highlight-symbol")
    (checked "centered-cursor-mode")
    (checked "compile")
    (checked "doc-view")
    (checked "golden-ratio")
    (checked "grep")
    (checked "info+")
    (checked "open-junk-file")
    (checked "paradox")
    (checked "restart-emacs")
    (checked "smooth-scrolling")
    (checked "symbol-overlay")
    (checked "winum")
  ];
  "spacemacs-misc" = [
    (checked "devdocs")
    (checked "dumb-jump")
    (checked "request")
  ];
  "spacemacs-modeline" = [
    (checked "anzu")
    (checked "doom-modeline")
    (checked "fancy-battery")
    (checked "font-lock+")
    (checked "neotree")
    (checked "spaceline")
    (checked "spaceline-all-the-icons")
    (checked "symon")
    (checked "vim-powerline")
  ];
  "spacemacs-editing" = [
    (checked "aggressive-indent")
    (checked "avy")
    (checked "bracketed-paste")
    (checked "clean-aindent-mode")
    (checked "editorconfig")
    (checked "eval-sexp-fu")
    (checked "expand-region")
    (checked "hexl")
    (checked "hungry-delete")
    (checked "link-hint")
    (checked "lorem-ipsum")
    (checked "move-text")
    (checked "origami")
    (checked "password-generator")
    (checked "pcre2el")
    (checked "smartparens")
    (checked "spacemacs-whitespace-cleanup")
    (checked "string-inflection")
    (checked "undo-tree")
    (checked "uuidgen")
    (checked "ws-butler")
  ];
  "spacemacs-language" = [
    (checked "define-word")
    (checked "google-translate")
  ];
  "spacemacs-project" = [
    (checked "projectile")
  ];
  "spacemacs-layouts" = [
    (checked "eyebrowse")
    (checked "helm")
    (checked "ivy")
    (checked "persp-mode")
    (checked "spaceline")
    (checked "counsel-projectile")
  ];
  "speed-reading" = [
    (checked "spray")
    (checked "which-key")
  ];
  "pdf" = [
    (checked "pdf-tools")
  ];
  "elfeed" = [
    (checked "elfeed")
    (checked "elfeed-goodies")
    (checked "elfeed-org")
    (checked "elfeed-web")
  ];
  "dash" = [
    (checked "dash-at-point")
    (checked "helm-dash")
    (checked "counsel-dash")
    (checked "zeal-at-point")
  ];
  "deft" = [
    (checked "deft")
  ];
  "epub" = [
    (checked "nov")
  ];
  "xkcd" = [
    (checked "xkcd")
  ];
  "selectric" = [
    (checked "selectric-mode")
  ];
  "emoji" = [
    (checked "emoji-cheat-sheet-plus")
    (checked "emojify")
    (checked "company-emoji")
  ];
  "games" = [
    (checked "2048-game")
    (checked "helm-games")
    (checked "pacmacs")
    (checked "tetris")
    (checked "sudoku")
    (checked "typit")
  ];
  "theming" = [
    (checked "theming")
  ];
  "colors" = [
    (checked "nyan-mode")
    (checked "color-identifiers-mode")
    (checked "rainbow-identifiers")
    (checked "rainbow-mode")
  ];
  "themes-megapack" = [
    (checked "afternoon-theme")
    (checked "alect-themes")
    (checked "ample-theme")
    (checked "ample-zen-theme")
    (checked "apropospriate-theme")
    (checked "anti-zenburn-theme")
    (checked "badwolf-theme")
    (checked "birds-of-paradise-plus-theme")
    (checked "bubbleberry-theme")
    (checked "busybee-theme")
    (checked "cherry-blossom-theme")
    (checked "chocolate-theme")
    (checked "clues-theme")
    (checked "color-theme-sanityinc-solarized")
    (checked "color-theme-sanityinc-tomorrow")
    (checked "cyberpunk-theme")
    (checked "dakrone-theme")
    (checked "darkburn-theme")
    (checked "darkmine-theme")
    (checked "darkokai-theme")
    (checked "darktooth-theme")
    (checked "django-theme")
    (checked "doom-themes")
    (checked "dracula-theme")
    (checked "espresso-theme")
    (checked "exotica-theme")
    (checked "eziam-theme")
    (checked "farmhouse-theme")
    (checked "flatland-theme")
    (checked "flatui-theme")
    (checked "gandalf-theme")
    (checked "gotham-theme")
    (checked "grandshell-theme")
    (checked "gruber-darker-theme")
    (checked "gruvbox-theme")
    (checked "hc-zenburn-theme")
    (checked "hemisu-theme")
    (checked "heroku-theme")
    (checked "inkpot-theme")
    (checked "ir-black-theme")
    (checked "jazz-theme")
    (checked "jbeans-theme")
    (checked "kaolin-themes")
    (checked "light-soap-theme")
    (checked "lush-theme")
    (checked "madhat2r-theme")
    (checked "majapahit-theme")
    (checked "material-theme")
    (checked "minimal-theme")
    (checked "moe-theme")
    (checked "molokai-theme")
    (checked "monokai-theme")
    (checked "monochrome-theme")
    (checked "mustang-theme")
    (checked "naquadah-theme")
    (checked "noctilux-theme")
    (checked "obsidian-theme")
    (checked "occidental-theme")
    (checked "omtose-phellack-theme")
    (checked "oldlace-theme")
    (checked "organic-green-theme")
    (checked "phoenix-dark-mono-theme")
    (checked "phoenix-dark-pink-theme")
    (checked "planet-theme")
    (checked "professional-theme")
    (checked "purple-haze-theme")
    (checked "railscasts-theme")
    (checked "rebecca-theme")
    (checked "reverse-theme")
    (checked "seti-theme")
    (checked "smyx-theme")
    (checked "soft-charcoal-theme")
    (checked "soft-morning-theme")
    (checked "soft-stone-theme")
    (checked "solarized-theme")
    (checked "soothe-theme")
    (checked "spacegray-theme")
    (checked "subatomic-theme")
    (checked "subatomic256-theme")
    (checked "sublime-themes")
    (checked "sunny-day-theme")
    (checked "tango-2-theme")
    (checked "tango-plus-theme")
    (checked "tangotango-theme")
    (checked "tao-theme")
    (checked "toxi-theme")
    (checked "twilight-anti-bright-theme")
    (checked "twilight-bright-theme")
    (checked "twilight-theme")
    (checked "ujelly-theme")
    (checked "underwater-theme")
    (checked "white-sand-theme")
    (checked "zen-and-art-theme")
    (checked "zenburn-theme")
  ];
  "ietf" = [
    (checked "ietf-docs")
    (checked "irfc")
    (checked "ox-rfc")
  ];
  "copy-as-format" = [
    (checked "copy-as-format")
  ];
  "multiple-cursors" = [
    (checked "evil-mc")
    (checked "multiple-cursors")
  ];
  "parinfer" = [
    (checked "parinfer")
  ];
  "nlinum" = [
  ];
  "chinese" = [
    (checked "pyim")
    (checked "chinese-wbim")
    (checked "fcitx")
    (checked "find-by-pinyin-dired")
    (checked "ace-pinyin")
    (checked "pangu-spacing")
    (checked "org")
    (checked "youdao-dictionary")
    (checked "chinese-conv")
  ];
  "japanese" = [
    (checked "evil-tutor-ja")
    (checked "migemo")
    (checked "avy-migemo")
    (checked "ddskk")
    (checked "japanese-holidays")
    (checked "pangu-spacing")
    (checked "org")
  ];
  "keyboard-layout" = [
    (checked "ace-window")
    (checked "avy")
    (checked "comint")
    (checked "company")
    (checked "elfeed")
    (checked "evil")
    (checked "evil-escape")
    (checked "evil-evilified-state")
    (checked "evil-magit")
    (checked "evil-surround")
    (checked "eyebrowse")
    (checked "flycheck")
    (checked "helm")
    (checked "imenu-list")
    (checked "ivy")
    (checked "magit")
    (checked "mu4e")
    (checked "neotree")
    (checked "org")
    (checked "org-agenda")
    (checked "ranger")
    (checked "twittering-mode")
    (checked "undo-tree")
  ];
  "version-control" = [
    (checked "browse-at-remote")
    (checked "diff-hl")
    (checked "diff-mode")
    (checked "evil-unimpaired")
    (checked "git-gutter")
    (checked "git-gutter-fringe")
    (checked "git-gutter+")
    (checked "git-gutter-fringe+")
    (checked "smerge-mode")
    (checked "vc")
  ];
  "git" = [
    (checked "evil-magit")
    (checked "fill-column-indicator")
    (checked "gitattributes-mode")
    (checked "gitconfig-mode")
    (checked "gitignore-mode")
    (checked "gitignore-templates")
    (checked "git-commit")
    (checked "git-link")
    (checked "git-messenger")
    (checked "git-timemachine")
    (checked "golden-ratio")
    (checked "helm-git-grep")
    (checked "helm-gitignore")
    (checked "magit")
    (checked "magit-gitflow")
    (checked "magit-section")
    (checked "magit-svn")
    (checked "org")
    (checked "orgit")
    (checked "smeargle")
    (checked "transient")
  ];
  "perforce" = [
    (checked "p4")
  ];
  "github" = [
    (checked "forge")
    (checked "gist")
    (checked "github-clone")
    (checked "github-search")
    (checked "spacemacs-github")
  ];
  "unicode-fonts" = [
    (checked "unicode-fonts")
    (checked "persistent-soft")
  ];
  "jabber" = [
    (checked "jabber")
    (checked "window-purpose")
  ];
  "erc" = [
    (checked "company")
    (checked "company-emoji")
    (checked "emoji-cheat-sheet-plus")
    (checked "erc")
    (checked "erc-gitter")
    (checked "erc-hl-nicks")
    (checked "erc-image")
    (checked "erc-sasl")
    (checked "erc-social-graph")
    (checked "erc-terminal-notifier")
    (checked "erc-tex")
    (checked "erc-view-log")
    (checked "erc-yank")
    (checked "erc-yt")
    (checked "linum")
    (checked "persp-mode")
    (checked "window-purpose")
  ];
  "slack" = [
    (checked "alert")
    (checked "emoji-cheat-sheet-plus")
    (checked "flyspell")
    (checked "linum")
    (checked "persp-mode")
    (checked "slack")
    (checked "window-purpose")
  ];
  "rcirc" = [
    (checked "company")
    (checked "company-emoji")
    (checked "emoji-cheat-sheet-plus")
    (checked "emojify")
    (checked "erc-image")
    (checked "erc-tweet")
    (checked "erc-yt")
    (checked "flyspell")
    (checked "helm-rcirc")
    (checked "persp-mode")
    (checked "rcirc")
    (checked "rcirc-color")
    (checked "rcirc-late-fix")
    (checked "rcirc-notify")
    (checked "rcirc-styles")
    (checked "window-purpose")
  ];
  "cscope" = [
    (checked "helm-cscope")
    (checked "xcscope")
  ];
  "gtags" = [
    (checked "ggtags")
    (checked "counsel-gtags")
    (checked "helm-gtags")
  ];
  "notmuch" = [
    (checked "counsel-notmuch")
    (checked "helm-notmuch")
    (checked "notmuch")
    (checked "org")
    (checked "persp-mode")
    (checked "window-purpose")
  ];
  "mu4e" = [
    (checked "mu4e")
    (checked "mu4e-alert")
    (checked "mu4e-maildirs-extension")
    (checked "helm-mu")
    (checked "org")
    (checked "persp-mode")
    (checked "window-purpose")
  ];
  "gnus" = [
    (checked "gnus")
    (checked "window-purpose")
    (checked "persp-mode")
  ];
  "prettier" = [
    (checked "prettier-js")
  ];
  "quickurl" = [
  ];
  "cmake" = [
    (checked "cmake-ide")
    (checked "cmake-mode")
    (checked "company")
    (checked "helm-ctest")
  ];
  "debug" = [
    (checked "realgud")
  ];
  "ranger" = [
    (checked "dired")
    (checked "golden-ratio")
    (checked "ranger")
  ];
  "imenu-list" = [
    (checked "golden-ratio")
    (checked "imenu-list")
  ];
  "systemd" = [
    (checked "flycheck")
    (checked "systemd")
  ];
  "elasticsearch" = [
    (checked "company")
    (checked "org")
    (checked "es-mode")
  ];
  "node" = [
    (checked "add-node-modules-path")
  ];
  "xclipboard" = [
    (checked "spacemacs-xclipboard")
    (checked "cliphist")
  ];
  "tern" = [
    (checked "company-tern")
    (checked "tern")
  ];
  "kubernetes" = [
    (checked "kubernetes")
    (checked "kubernetes-evil")
  ];
  "shell" = [
    (checked "comint")
    (checked "company")
    (checked "esh-help")
    (checked "eshell")
    (checked "eshell-prompt-extras")
    (checked "eshell-z")
    (checked "helm")
    (checked "ivy")
    (checked "magit")
    (checked "multi-term")
    (checked "org")
    (checked "projectile")
    (checked "shell")
    (checked "shell-pop")
    (checked "term")
    (checked "xterm-color")
    (checked "terminal-here")
    (checked "vi-tilde-fringe")
    (checked "vterm")
  ];
  "sailfish-developer" = [
    (checked "sailfish-scratchbox")
  ];
  "dap" = [
    (checked "dap-mode")
  ];
  "command-log" = [
    (checked "command-log-mode")
  ];
  "import-js" = [
    (checked "import-js")
  ];
  "web-beautify" = [
    (checked "web-beautify")
  ];
  "ansible" = [
    (checked "ansible")
    (checked "ansible-doc")
    (checked "company")
    (checked "company-ansible")
    (checked "jinja2-mode")
    (checked "yaml-mode")
  ];
  "vagrant" = [
    (checked "vagrant")
    (checked "vagrant-tramp")
  ];
  "restclient" = [
    (checked "company-restclient")
    (checked "golden-ratio")
    (checked "ob-http")
    (checked "ob-restclient")
    (checked "restclient")
    (checked "restclient-helm")
  ];
  "nginx" = [
    (checked "nginx-mode")
  ];
  "docker" = [
    (checked "docker")
    (checked "docker-tramp")
    (checked "dockerfile-mode")
    (checked "flycheck")
  ];
  "puppet" = [
    (checked "company")
    (checked "flycheck")
    (checked "puppet-mode")
  ];
  "fasd" = [
    (checked "fasd")
  ];
  "lsp" = [
    (checked "lsp-mode")
    (checked "lsp-ui")
    (checked "company-lsp")
    (checked "helm-lsp")
    (checked "lsp-treemacs")
    (checked "popwin")
  ];
  "bm" = [
    (checked "bm")
  ];
  "chrome" = [
    (checked "edit-server")
    (checked "gmail-message-mode")
    (checked "flymd")
    (checked "markdown-mode")
  ];
  "cfengine" = [
    (checked "cfengine3-mode")
    (checked "company")
    (checked "eldoc")
    (checked "flycheck")
    (checked "ob-cfengine3")
    (checked "org")
  ];
  "finance" = [
    (checked "company")
    (checked "flycheck-ledger")
    (checked "ledger-mode")
    (checked "evil-ledger")
  ];
  "sphinx" = [
    (checked "rst")
    (checked "rst-sphinx")
  ];
  "salt" = [
    (checked "salt-mode")
    (checked "smartparens")
  ];
  "transmission" = [
    (checked "transmission")
  ];
  "terraform" = [
    (checked "company-terraform")
    (checked "terraform-mode")
  ];
  "rebox" = [
    (checked "rebox2")
  ];
  "pass" = [
    (checked "ivy-pass")
    (checked "helm-pass")
    (checked "password-store")
  ];
  "dotnet" = [
    (checked "dotnet")
  ];
  "pandoc" = [
    (checked "pandoc-mode")
    (checked "ox-pandoc")
  ];
  "tmux" = [
    (checked "golden-ratio")
    (checked "tmux")
  ];
  "geolocation" = [
    (checked "osx-location")
    (checked "popwin")
    (checked "rase")
    (checked "sunshine")
    (checked "theme-changer")
  ];
  "prodigy" = [
    (checked "prodigy")
  ];
  "typography" = [
    (checked "tildify")
    (checked "typo")
  ];
  "helpful" = [
    (checked "helpful")
  ];
  "ibuffer" = [
    (checked "ibuffer")
    (checked "ibuffer-projectile")
  ];
  "smex" = [
    (checked "smex")
  ];
  "better-defaults" = [
    (checked "mwim")
    (checked "unfill")
  ];
  "semantic" = [
    (checked "semantic")
    (checked "srefactor")
    (checked "stickyfunc-enhance")
  ];
  "org" = [
    (checked "company")
    (checked "company-emoji")
    (checked "emoji-cheat-sheet-plus")
    (checked "evil-org")
    (checked "evil-surround")
    (checked "gnuplot")
    (checked "helm-org")
    (checked "helm-org-rifle")
    (checked "htmlize")
    (checked "ob")
    (checked "org")
    (checked "org-agenda")
    (checked "org-brain")
    (checked "org-expiry")
    (checked "org-journal")
    (checked "org-download")
    (checked "org-jira")
    (checked "org-mime")
    (checked "org-pomodoro")
    (checked "org-present")
    (checked "org-cliplink")
    (checked "org-projectile")
    (checked "ox-epub")
    (checked "ox-twbs")
    (checked "ox-gfm")
    (checked "org-re-reveal")
    (checked "persp-mode")
    (checked "ox-hugo")
    (checked "ox-jira")
    (checked "org-trello")
    (checked "org-sticky-header")
  ];
  "vim-empty-lines" = [
    (checked "vim-empty-lines-mode")
    (checked "vi-tilde-fringe")
  ];
  "evil-commentary" = [
    (checked "evil-commentary")
    (checked "evil-nerd-commenter")
  ];
  "vinegar" = [
    (checked "diff-hl")
    (checked "dired")
  ];
  "evil-snipe" = [
    (checked "evil-snipe")
    (checked "magit")
    (checked "ranger")
  ];
  "neotree" = [
    (checked "neotree")
    (checked "winum")
  ];
  "treemacs" = [
    (checked "golden-ratio")
    (checked "treemacs")
    (checked "treemacs-evil")
    (checked "treemacs-magit")
    (checked "treemacs-persp")
    (checked "treemacs-projectile")
    (checked "winum")
  ];
  "spacemacs-bootstrap" = [
    (checked "async")
    (checked "bind-map")
    (checked "bind-key")
    (checked "diminish")
    (checked "evil")
    (checked "hydra")
    (checked "use-package")
    (checked "which-key")
    (checked "dotenv-mode")
    (checked "evil-evilified-state")
    (checked "pcre2el")
    (checked "holy-mode")
    (checked "hybrid-mode")
    (checked "spacemacs-theme")
  ];
  "spacemacs-base" = [
  ];
  "spacemacs" = [
  ];
  "spacemacs-docker" = [
  ];
}
