#!/usr/bin/env nix-shell
#! nix-shell -i "emacs --batch -l $HOME/.emacs.d/core/core-load-paths.el -l" -p emacs26-nox

(load (concat spacemacs-core-directory "core-versions.el"))
(require 'core-configuration-layer)
(configuration-layer/discover-layers)
(configuration-layer/make-all-packages nil)

(princ "# Generated by spacemacs2nix.el\n")
(princ "p:\n")
(princ "let checked = n:\n")
(princ "  let\n")
(princ "    n' = builtins.replaceStrings [\"+\"] [\"-plus\"] n;\n")
(princ "    p' = p.${n'} or null;\n")
(princ "  in if p'.meta.broken or false then null else p';\n")
(princ "in\n")
(princ "{\n")
(dolist (layer-symbol (configuration-layer/get-layers-list))
  (princ (concat "  " (prin1-to-string (symbol-name layer-symbol)) " = [\n"))
  (let* ((layer (configuration-layer/get-layer layer-symbol)))
    (dolist (pkg (cfgl-layer-get-packages layer 'with-props))
      (princ (concat "    (checked " (prin1-to-string (symbol-name (if (listp pkg) (car pkg) pkg))) ")\n"))))
  (princ "  ];\n"))
(princ "}\n")
