name: "Update Flake inputs + nvim plugins"
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "38 0 * * *"
    - cron: "38 6 * * *"
    - cron: "38 12 * * *"
    - cron: "38 18 * * *"
jobs:
  update-everything:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: cachix/install-nix-action@v31
      - run: nix flake update
      - name: Update vim plugins
        run: |
          nix run .#nvim -- --headless "+Lazy! update" +qa
          cp $HOME/.config/nvim-mic92/lazy-lock.json home/.config/nvim/lazy-lock.json
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.CI_APP_ID }}
          private-key: ${{ secrets.CI_PRIVATE_KEY }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Update flakes and vim plugins
          token: ${{ steps.app-token.outputs.token }}
          labels: |
            auto-merge
