[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "claude-md"
version = "0.1.0"
description = "CLI tool to manage CLAUDE.local.md files across repositories"

[project.scripts]
claude-md = "claude_md:main"

[tool.hatch.build.targets.wheel]
packages = ["claude_md.py"]